### ISSUE TITLE
Syntax highlighting no longer working on 0.2.3

### ISSUE THREAD

**Issue by ethanjones** [CityOfEscondido/Visual-Studio-Code-SQR#3]
The syntax highlighting quit working after upgrading the extension to 0.2.3.

**Comment by abasic-csu** [comment]
yeah, it's not working for me either. looks like `\\b(\\s+)?(?i:\\b` is the culprit. The extra keywords added aren't an issue. Changing that back to` \\b(?i:\\b` fixes the problem..

**Comment by coe-jeubanks** [comment]
Thanks for the report. There were some null characters embedded in the syntax file, and that seems to have been interfering with the parsing engine. I rebuilt the file to get rid of those, and all seems well now. I've pushed 0.2.4 up to the marketplace.
