### ISSUE TITLE
VSCode hangs when opening moderately large SQRs

### ISSUE THREAD

**Issue by abasic-csu** [CityOfEscondido/Visual-Studio-Code-SQR#5]
Since the latest release of Code opening a file with ~2000 LOC causes it to hang for about 6 or 7 seconds. If I disable the extension, Code works fine however. I'm guessing this is probably a regex issue?  I'll have a look to see if anything stands out, but my regex fu could do with some work.

In the mean time, is anyone else encountered this with the new version? I'm using the 64bit edition FWIW.

**Comment by coe-jeubanks** [comment]
That's odd. I installed the x64 version earlier this week, and I haven't seen that particular issue. One thing I did notice is that the first time I launch Code, it takes it a while to start and load the file, perhaps 4-5 seconds here. But once I have it open, if I right-click an SQR and open it, it's nearly instantly ready to go. The largest one I have here is 414KB (9,300 lines), and it comes up instantly (as long as Code is already open).

If you can find anything special about that particular SQR that causes a slowdown as compared to others, let me know and I'll investigate further.

**Comment by abasic-csu** [comment]
Sorry, somewhat forgot about this. The issue seems to have gone away by itself so I'll close it for now and if it pops up again try to figure out what's going on and include some further details in a new issue.
