### ISSUE TITLE
_# causes vsc to lock up

### ISSUE THREAD

**Issue by RameshKris** [CityOfEscondido/Visual-Studio-Code-SQR#7]
Using _# in the file causes VSC to lock up.
Steps to reproduce. Open a test.sqr file, 
type "_#"

Issues seems to be a conflict with 

 {  "name": "keyword.include.SQR",
       "match": "(\\s)\*(#)(?i:include)\\s"
    },
    {  "name": "storage.type.SQR",
       "match": "(\\s)\*(#)(?i:define)\\s"
    },

this fixed it.
   {  "name": "keyword.include.SQR",
       "match": "#(?i:include)\\b"
    },
      {  "name": "storage.type.SQR",
       "match": "(#)(?i:define)\\b"
    },

**Comment by coe-jeubanks** [comment]
Thanks for this! It's only a problem in the x64 version of VSCode, and I've had an [issue open in vscode-textmate about this](https://github.com/Microsoft/vscode-textmate/issues/56). I'll reference your workaround over there and get the extension updated with this change.

**Comment by coe-jeubanks** [comment]
I've pushed a new release of the extension to the marketplace.
