### ISSUE TITLE
Numeric without word boundary causing number to highlight

### ISSUE THREAD

**Issue by RameshKris** [CityOfEscondido/Visual-Studio-Code-SQR#8]
Numeric without word boundary causing number to highlight , in procedure, variables names

     {
            "name": "constant.numeric.SQR",
            "match": "\\b([\\d]+(\\.?)[\\d]+)\\b"
        },

**Comment by coe-jeubanks** [comment]
Thanks for the contribution. I've pushed to repo and published an updated version of the extension.
